SELECT     PROD_CD, CASE WHEN (AVAIL_01 IS NULL) THEN 0 ELSE AVAIL_01 END AS AVAIL01, CASE WHEN (AVAIL_05 IS NULL)
                      THEN 0 ELSE AVAIL_05 END AS AVAIL05, CASE WHEN (AVAIL_07 IS NULL) THEN 0 ELSE AVAIL_07 END AS AVAIL07, CASE WHEN (AVAIL_20 IS NULL)
                      THEN 0 ELSE AVAIL_20 END AS AVAIL20, CASE WHEN (INSTK_01 IS NULL) THEN 0 ELSE INSTK_01 END AS INSTK01, CASE WHEN (INSTK_05 IS NULL)
                       THEN 0 ELSE INSTK_05 END AS INSTK05, CASE WHEN (INSTK_07 IS NULL) THEN 0 ELSE INSTK_07 END AS INSTK07,
                      CASE WHEN (INSTK_20 IS NULL) THEN 0 ELSE INSTK_20 END AS INSTK20, CASE WHEN (PO_01 IS NULL) THEN 0 ELSE PO_01 END AS PO01,
                      CASE WHEN (PO_05 IS NULL) THEN 0 ELSE PO_05 END AS PO05, CASE WHEN (PO_07 IS NULL) THEN 0 ELSE PO_07 END AS PO07,
                      CASE WHEN (PO_20 IS NULL) THEN 0 ELSE PO_20 END AS PO20, CASE WHEN (OTW_01 IS NULL) THEN 0 ELSE OTW_01 END AS OTW01,
                      CASE WHEN (OTW_05 IS NULL) THEN 0 ELSE OTW_05 END AS OTW05, CASE WHEN (OTW_07 IS NULL) THEN 0 ELSE OTW_07 END AS OTW07,
                      CASE WHEN (OTW_20 IS NULL) THEN 0 ELSE OTW_20 END AS OTW20, CASE WHEN (ORD_01 IS NULL) THEN 0 ELSE ORD_01 END AS ORD01,
                      CASE WHEN (ORD_05 IS NULL) THEN 0 ELSE ORD_05 END AS ORD05, CASE WHEN (ORD_07 IS NULL) THEN 0 ELSE ORD_07 END AS ORD07,
                      CASE WHEN (ORD_20 IS NULL) THEN 0 ELSE ORD_20 END AS ORD20
FROM         omsdata2.dbo.HL_SUM_INV_DATA_1
