SELECT     TOP (100) PERCENT PROD_CD, CASE WHS_NUM WHEN ('06') THEN SUM(IN_STOCK) - (SUM(BACK_QTY) + SUM(ORDER_QTY)) END AS AVAIL_06,
                      CASE WHS_NUM WHEN ('06') THEN SUM(IN_STOCK) END AS INSTK_06,
                      CASE WHS_NUM WHEN ('06') THEN SUM(ON_ORDER_QTY) END AS PO_06,
                      CASE WHS_NUM WHEN ('06') THEN SUM(WATER_QTY) END AS OTW_06,
                      CASE WHS_NUM WHEN ('06') THEN SUM(ORDER_QTY) END AS ORD_06
FROM         omsdata2.dbo.inv_data
GROUP BY PROD_CD, WHS_NUM
ORDER BY PROD_CD, WHS_NUM
