SELECT     TOP (100) PERCENT PROD_CD, SUM(AV01) + SUM(AV20) AS AVAIL_WEST,
SUM(AV05) + SUM(AV07) AS AVAIL_EAST,
SUM(IN01) + SUM(IN20) AS INSTK_WEST,
SUM(IN05) + SUM(IN07) AS INSTK_EAST,
SUM(PO01) + SUM(PO20) AS PO_WEST,
SUM(PO05) + SUM(PO07) AS PO_EAST,
SUM(OT01) + SUM(OT20) AS OTW_WEST,
SUM(OT05) + SUM(OT07) AS OTW_EAST,
SUM(OR01) + SUM(OR20) AS ORD_WEST,
SUM(OR05) + SUM(OR07) AS ORD_EAST,
SUM(AV01) + SUM(AV20) + SUM(AV05) + SUM(AV07) AS AVAIL_ALL,
                          (SELECT     TOP (1) CLASS_CD
                            FROM          omsdata2.dbo.inv
                            WHERE      (PROD_CD = omsdata2.dbo.HL_SUM_INV_DATA_2.PROD_CD)) AS CLASSCODE
FROM         omsdata2.dbo.HL_SUM_INV_DATA_2
GROUP BY PROD_CD
ORDER BY PROD_CD
